### ISSUE TITLE
GitHub actualizó la version de Jekyll

### ISSUE THREAD

**Issue by edittler** [fiuba-apuntes/fiuba-apuntes.github.io#1]
Como lo han notificado en su [blog](https://github.com/blog/2100-github-pages-jekyll-3), han actualizado el soporte a Jekyll 3. Esa versión tiene cambios que no son compatibles con versiones anteriores. Verificar que funcione y corregir en caso de que sea necesario.

**Comment by miparnisari** [comment]
Cuando haces clicks en los departamentos no se ven las materias :cry:

**Comment by lucasp90** [comment]
A mí me pasa que a veces tengo que recargar la página para que se vean las materias.

**Comment by miparnisari** [comment]
Nop, yo probe y no me funciona. En la consola veo este error:

`jquery.js:1458 Uncaught Error: Syntax error, unrecognized expression: [data-"Times New Roman"-slider]`

**Comment by edittler** [comment]
Parece ser que es un problema entre Foundation y jQuery. Recién subí un fix al problema.
Jekyll 3 parece andar sin problemas  :smile:

**Comment by edittler** [comment]
Hace tiempo está corriendo Jekyll 3 y el sitio parece andar bien. Cierro el issue.
