### ISSUE TITLE
No se despliegan las materias al clickear sobre el acordeón de los departamentos

### ISSUE THREAD

**Issue by lucasp90** [fiuba-apuntes/fiuba-apuntes.github.io#2]
## Pasos para reproducir
1. Ingresar al sitio
2. Seleccionar la opción "Apuntes"
3. Clickear sobre cualquier departamento
## Problema

El sitio no despliega las materias con sus correspondientes apuntes. En la consola puede verse el siguiente error: `jquery.js:1458 Uncaught Error: Syntax error, unrecognized expression: [data-"Times New Roman"-slider]`

Identificado por @miparnisari en [este comentario](https://github.com/fiuba-apuntes/fiuba-apuntes.github.io/issues/1#issuecomment-231566275)

**Comment by miparnisari** [comment]
Arreglado :)

**Comment by lucasp90** [comment]
Se cierra por el fix indicado en [este comentario](https://github.com/fiuba-apuntes/fiuba-apuntes.github.io/issues/1#issuecomment-231570808)
